# 通用扩展
- repo: tpope/vim-surround
- repo: tpope/vim-repeat
- repo: tpope/vim-commentary
- repo: jeffkreeftmeijer/vim-numbertoggle

# 快选择代码块
# - repo: gcmt/wildfire.vim

# 多光标
# - repo: mg979/vim-visual-multi

# - repo: tveskag/nvim-blame-line
#   hook_add: |-
#     let g:blameLineVirtualTextFormat = '     %s'
#     let g:blameLineGitFormat = ' %an ⏽  %as ⏽  %s ⏽ %h'

# 代码补全&分析
- repo: neoclide/coc.nvim
  merged: 0
