# 通用扩展
- repo: tpope/vim-surround
- repo: tpope/vim-repeat
- repo: tpope/vim-commentary
- repo: jeffkreeftmeijer/vim-numbertoggle

# 快选择代码块
# - repo: gcmt/wildfire.vim

# 多光标
- repo: mg979/vim-visual-multi

# vim-tmux 导航
- repo: christoomey/vim-tmux-navigator
  if: "! (has('win32') || has('win64'))"
  hook_source: source $VIM_PATH/config/plugins/vim-tmux-navigator.vim
